/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.cg;

import java.util.*;
import java.util.regex.Pattern;

public class UserRegistration {
	static Scanner sc = new Scanner(System.in);
	static String namePattern = "^[A-Z]{1}[A-Za-z]{2,}";
	static String emailPattern = "^[a-zA-Z0-9+_-]+([.][a-zA-Z0-9]+)*@([a-zA-Z0-9]+)([.][a-z]+)?[.][a-z]{2,}$";
	static String phoneNumberPattern = "^[0-9]{1,}[ ][1-9][0-9]{9}$";
	static String passwordPattern = "^(?=.*[A-Z])(?=.*[0-9]).{8,}$";

	public static boolean firstNameValidator(String firstName) {
		return Pattern.matches(namePattern, firstName);
	}

	public static boolean lastNameValidator(String lastName) {
		return Pattern.matches(namePattern, lastName);
	}

	public static boolean emailValidator(String email) {
		return Pattern.matches(emailPattern, email);
	}

	public static boolean phoneNumberValidator(String phoneNumber) {
		return Pattern.matches(phoneNumberPattern, phoneNumber);
	}

	public static boolean passwordValidator(String password) {
		return Pattern.matches(passwordPattern, password);
	}

	public static void main(String[] args) {
		System.out.println("User Registration Program with validation");
		String firstName;
		String lastName;
		String email;
		String phoneNumber;
		String password;

		boolean match = false;
		System.out.println("Enter the first name:");
		while (!match) {
			firstName = sc.nextLine();
			match = firstNameValidator(firstName);
			if (!match)
				System.out.println("Invalid First Name, Please enter again (First letter capital, minimum 3 letters)");
		}
		System.out.println("First Name is added successfully\n");

		match = false;
		System.out.println("Enter the last name:");
		while (!match) {
			lastName = sc.nextLine();
			match = lastNameValidator(lastName);
			if (!match)
				System.out.println("Invalid Last Name, Please enter again (First letter capital, minimum 3 letters)");
		}
		System.out.println("Last Name is added successfully\n");

		match = false;
		System.out.println("Enter the email:");
		while (!match) {
			email = sc.nextLine();
			match = emailValidator(email);
			if (!match)
				System.out.println("Invalid email, Please enter again (First letter capital, minimum 3 letters)");
		}
		System.out.println("Email is added successfully\n");

		match = false;
		System.out.println("Enter the Phone Number:");
		while (!match) {
			phoneNumber = sc.nextLine();
			match = phoneNumberValidator(phoneNumber);
			if (!match)
				System.out.println("Invalid phone Number, Please enter a valid phone Number)");
		}
		System.out.println("Phone Number is added successfully\n");

		match = false;
		System.out.println("Enter the Password:");
		while (!match) {
			password = sc.nextLine();
			match = passwordValidator(password);
			if (!match)
				System.out.println("Invalid password format, Please enter a valid password)");
		}
		System.out.println("Password is added successfully\n");
	}
}
